{% set name = "solana" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solana-{{ version }}.tar.gz
  sha256: 699a9e6f02bbe3d16da6a8e3c472a94e0eba0b2e5c570fbc9e57f1baec4ce8ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - base58 >=2.0.1
    - construct >=2.10.56
    - pynacl >=1.4
    - python >=3.7
    - requests >=2.24.0
    - typing-extensions
    - httpx >=0.18.2

test:
  imports:
    - solana
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michaelhly/solana-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Solana Python SDK
  description: |
    Solana Python API built on the JSON RPC API.

    Python version of solana-web3.js for interacting with Solana.
  doc_url: https://michaelhly.github.io/solana-py/
  dev_url: https://github.com/michaelhly/solana-py

extra:
  recipe-maintainers:
    - kevinheavey
