{% set name = "solana" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solana-{{ version }}.tar.gz
  sha256: 4dfb2ce0f361ab75da41257f81d5e54dbadd78ef11028e48183baad450f87de5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --use-deprecated=out-of-tree-build

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7
  run:
    - base58 >=2.0.1
    - cachetools >=4.2.2,<5.0.0
    - construct >=2.10.56
    - construct-typing >=0.5.2
    - pynacl >=1.4
    - python >=3.7
    - requests >=2.24.0
    - typing-extensions >=3.10.0,<4.0.0
    - types-cachetools >=4.2.4,<5.0.0
    - httpx >=0.18.2,<0.19.0

test:
  imports:
    - solana
    - spl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michaelhly/solana-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Solana Python SDK
  description: |
    Solana Python API built on the JSON RPC API.

    Python version of solana-web3.js for interacting with Solana.
  doc_url: https://michaelhly.github.io/solana-py/
  dev_url: https://github.com/michaelhly/solana-py

extra:
  recipe-maintainers:
    - kevinheavey
